apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "phoenix.selectorLabels" . | nindent 6 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector: 
    {{- include "phoenix.selectorLabels" . | nindent 8 }}
